/*
 * @(#)lmslabels_de.js 1.1.5  2003-11-05
 *
 * Copyright (c) 2003 Werner Randelshofer
 * Staldenmattweg 2, Immensee, CH-6405, Switzerland
 * All rights reserved.
 *
 * This software is the confidential and proprietary information of 
 * Werner Randelshofer. ("Confidential Information").  You shall not
 * disclose such Confidential Information and shall use it only in
 * accordance with the terms of the license agreement you entered into
 * with Werner Randelshofer.
 */

/**
 * This file contains locale dependent labels for TinyLMS.
 * This is the set of german labels. Language code "de".
 *
 * This file is intended to be included in the top level frameset of an 
 * eLearning course generated by TinyLMS.
 *
 * Example:
 * <html>
 *   <head>
 *     <title>Learning Management System</title>
 *     <script language="JavaScript" src="tinylms/lib/collections.js" type="text/JavaScript"></script>
 *     <script language="JavaScript" src="tinylms/lib/lmsapi.js" type="text/JavaScript"></script>
 *     <script language="JavaScript" src="tinylms/lib/lmslabels.js" type="text/JavaScript"></script>
 *   </head>
 * </html>
 */
API.labels = new Map();
API.labels.importFromArray([
["login.url",'tinylms/lmslogin_de.html'],
["login.title","Willkommen"],
["login.welcome","Willkommen bei TinyLMS."],
["login.please","Bitte geben Sie Ihren Benutzernamen ein"],
["login.userid","Benutzername"],
["login.login","Anmelden"],
["toc.logoff","Abmelden"],
["login.baduserid","Bitte überprüfen Sie Ihren Benutzernamen."], // No HTML
["login.badpassword","Bitte überprüfen Sie Ihr Kennwort."], // No HTML
["toc.menu","Menu"],
["toc.previous","Zur&uuml;ck"],
["toc.next","Weiter"],
["statistics.title","Statistik"],
["statistics.pages","Seite"],
["statistics.viewed","Besucht"],
["statistics.passed","Bestanden"],
["statistics.pagesvisited","Sie haben {0} von {1} Seiten besucht."],
["statistics.pagesfailed","Sie haben {0} &Uuml;bungen nicht bestanden."],
["statistics.reset","Statistik zur&uuml;cksetzen"]
]);