/*
 * @(#)lmslabels_en.js 1.1.5  2003-11-05
 *
 * Copyright (c) 2003 Werner Randelshofer
 * Staldenmattweg 2, Immensee, CH-6405, Switzerland
 * All rights reserved.
 *
 * This software is the confidential and proprietary information of 
 * Werner Randelshofer. ("Confidential Information").  You shall not
 * disclose such Confidential Information and shall use it only in
 * accordance with the terms of the license agreement you entered into
 * with Werner Randelshofer.
 */

/**
 * This file contains locale dependent labels for TinyLMS.
 * This is the set of english labels. Language code "en".
 *
 * This file is intended to be included in the top level frameset of an 
 * eLearning course generated by TinyLMS.
 *
 * Example:
 * <html>
 *   <head>
 *     <title>Learning Management System</title>
 *     <script language="JavaScript" src="tinylms/lib/collections.js" type="text/JavaScript"></script>
 *     <script language="JavaScript" src="tinylms/lib/lmslabels.js" type="text/JavaScript"></script>
 *     <script language="JavaScript" src="tinylms/lib/lmslabels_en.js" type="text/JavaScript"></script>
 *   </head>
 * </html>
 */
API.labels = new Map();
API.labels.importFromArray([
["login.url",'tinylms/lmslogin_en.html'],
["login.title","Welcome"],
["login.welcome","Welcome to TinyLMS."],
["login.please","Please enter your user name."],
["login.userid","User Name:"],
["login.login","Login"],
["login.baduserid","Please verify your user id."], // No HTML
["login.badpassword","Please verify your password."], // No HTML
["toc.logoff","Logout"],
["toc.menu","Menu"],
["toc.previous","Previous"],
["toc.next","Next"],
["statistics.title","Statistics"],
["statistics.pages","Page"],
["statistics.viewed","Viewed"],
["statistics.passed","Passed"],
["statistics.pagesvisited","You have visited {0} of {1} pages."],
["statistics.pagesfailed","You failed {0} exercises."],
["statistics.reset","Reset"]
]);