/*
 * @(#)lmslayernav.js 1.0 2003-09-12
 *
 * Copyright (c) 2003 Werner Randelshofer
 * Staldenmattweg 2, Immensee, CH-6405, Switzerland
 * All rights reserved.
 *
 * This software is the confidential and proprietary information of 
 * Werner Randelshofer. ("Confidential Information").  You shall not
 * disclose such Confidential Information and shall use it only in
 * accordance with the terms of the license agreement you entered into
 * with Werner Randelshofer.
 *
 * 
 * The following conditions apply only, if this software is distributed 
 * as part of TinyLMS:
 *
 *      This program is free software; you can redistribute it and/or modify it 
 *      under the terms of the GNU General Public License as published by the 
 *      Free Software  Foundation; either version 2 of the License, or (at your
 *      option) any later version. 
 *
 *      This program is distributed in the hope that it will be useful, but 
 *      WITHOUT ANY WARRANTY; without even the implied warranty of 
 *      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
 *      Public License for more details. You should have received a copy of the
 *      GNU General Public License along with this program; if not, write to the
 *      Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
 *      02111-1307 USA
 */ 
/**
 * This scripts inserts a horizontal navigation bar at the current location
 * into a HTML document.
 *
 * This file is intended to be included in the body of a HTML document. The
 * HTML document must be in a child frame of the Learning Management System
 * generated by TinyLMS.
 *
 * Example:
 * <html>
 *   <head>
 *     <title>Table Of Contens</title>
 *     <script language="JavaScript" src="lib/lmscollections.js" type="text/JavaScript"></script>
 *     <script language="JavaScript" src="lib/lmsstub.js" type="text/JavaScript"></script>
 *     <script language="JavaScript" src="lib/lmslayernav.js" type="text/JavaScript"></script>
 *   </head>
 *   <body>
 *     <script language="JavaScript" type="text/JavaScript">nav.writeColumns()</script>
 *     <script language="JavaScript" type="text/JavaScript">nav.writeCells()</script>
 *     <script language="JavaScript" type="text/JavaScript">nav.writeButtons()</script>
 *   </body>
 * </html>
 *
 * @version 1.0 2003-09-12 Locale specific labels are now read from the API object.
 * 0.25 2003-08-11 Variable LMSlabels renamed to LMSLabels due to changes in lmslabels.js.
 * 0.24 2003-05-07 gotoNextRow() and gotoPreviousRow()
 * don't go automatically to the menu page anymore, when the user tries to 
 * go over the last or the first page of the tutorial.
 * 0.21 2003-04-08 Display 'page i of n' instead of numbers for cell indicators.
 * 0.20.2 2003-04-07 Display numbers instead of dots for cell indicators.
 * 0.19 2003-04-07 Created.
 */


/**
 * Writes the layers of the current organization.
 * The navigation bar entries are retrieved from the LMS using 
 * protected operations.
 */
function Nav_writeColumns() {
  document.write('<table border="0" cellspacing="0" cellpadding="0"><tr>');
	var api = stub.getAPI();
	if (api.isLoggedIn() && api.mode == api.MODE_COURSE) {
		var currentItem = api.getAnticipatedItem();
		if (currentItem == null) currentItem = api.getCurrentItem();
		var currentOrganization = api.getCurrentOrganization();
		var currentColumnName = api.getCurrentColumnName();
		var rowItem = currentOrganization.getRowOfItem(currentItem);
		if (rowItem == null) currentColumnName = "";

  	var columnNames = api.camColumnNames;
		for (var i=0; i < columnNames.length; i++) {
			//if (i != 0) document.write('<img src="images/spacer.gif" width="12" height="1" border="0">');

			  var columnItem = null;
		  	if (rowItem != null) {
			  	for (var j=0; j < rowItem.getChildCount(); j++) {
				  	if (rowItem.getChildAt(j).title == columnNames[i]) {
					  	columnItem = rowItem.getChildAt(j);
							break;
						}
					}
				}
		  	var refItem = null;
				if (columnItem != null) {
		  		refItem = columnItem;
					resource = refItem.getResource();
  				while (resource == null && refItem.getChildCount() != 0) {
    				refItem = refItem.getChildAt(0);
 						resource = refItem.getResource();
  				}
				}
				if (refItem == null) refItem = currentItem;

      if (columnItem == null) {
					document.write('<td width="92" height="18" align="center" valign="top" class="linkDisabled">');
					//document.write('<a class="linkDisabled" href="#" onClick="stub.getAPI().gotoItemWithID(\''+refItem.identifier+'\')">');
					//document.write('&nbsp;&nbsp;&nbsp;');
					document.write(columnNames[i]);
					//document.write('&nbsp;&nbsp;&nbsp;');
					//document.write('</a>');
					document.write('</td>');
			} else {
				if (columnNames[i] == currentColumnName) {
					document.write('<td width="92" height="18" align="center" valign="top" class="linkCurrent">');
					document.write('<a class="linkCurrent" href="#" onClick="stub.getAPI().gotoItemWithID(\''+refItem.identifier+'\')">');
					//document.write('&nbsp;&nbsp;&nbsp;');
					document.write(columnNames[i]);
					//document.write('&nbsp;&nbsp;&nbsp;');
					document.write('</a>');
					document.write('</td>');
				} else {
					if (refItem == null) {
						document.write('<td width="92" height="18" align="center" valign="top" class="linkDisabled">');
					//document.write('&nbsp;&nbsp;&nbsp;');
						document.write(columnNames[i]);
					//document.write('&nbsp;&nbsp;&nbsp;');
						document.write('</td>');
					} else {
						document.write('<td width="92" height="18" align="center" valign="top" class="link">');
						document.write('<a class="link" href="#" onClick="stub.getAPI().gotoItemWithID(\''+refItem.identifier+'\')">');
					//document.write('&nbsp;&nbsp;&nbsp;');
						document.write(columnNames[i]);
					//document.write('&nbsp;&nbsp;&nbsp;');
						document.write('</a>'); 
						document.write('</td>');
					}
				}
			}
		}
  }
	document.write('</tr></table>');
}
/**
 * Writes the cells of the current layer.
 * The cells are retrieved from the LMS using 
 * protected operations.
 * Writes 'page i of n' where 'i' is the index of the current cell + 1
 * and 'n' is the number of cells.
 */
function Nav_writeCells() {
	var api = stub.getAPI();
	if (api.isLoggedIn() && api.mode == api.MODE_COURSE) {
		var currentItem = api.getAnticipatedItem();
		if (currentItem == null) currentItem = api.getCurrentItem();
		var currentOrganization = api.getCurrentOrganization();
		var currentColumnName = api.getCurrentColumnName();
		var rowItem = currentOrganization.getRowOfItem(currentItem);

	  var columnItem = currentItem.getParent();
		if (columnItem != null) {
			var cellIndex = -1;
			if (columnItem != rowItem && currentItem != rowItem) {
				for (var i=0; i < columnItem.getChildCount(); i++) {
					if (columnItem.getChildAt(i) == currentItem) {
						cellIndex = i;
						break;
					}
				}
				document.write('<span class="button">');
				document.write((cellIndex + 1)+" von "+columnItem.getChildCount());
				document.write('</span>');
			} else {
				document.write('<span class="button">');
				document.write("1 von 1");
				document.write('</span>');
			}
		}
	}
}
/**
 * Writes the cells of the current layer.
 * The cells are retrieved from the LMS using 
 * protected operations.
 * Writes numbers for each cell. The current cell is written in bold.
 * /
function Nav_writeCellIndices() {
	var api = stub.getAPI();
	if (api.isLoggedIn()) {
		var currentItem = api.getAnticipatedItem();
		if (currentItem == null) currentItem = api.getCurrentItem();
		var currentOrganization = api.getCurrentOrganization();
		var currentColumnName = api.getCurrentColumnName();
		var rowItem = currentOrganization.getRowOfItem(currentItem);

	  var columnItem = currentItem.getParent();
		if (columnItem != rowItem && currentItem != rowItem) {
		  for (var i=0; i < columnItem.getChildCount(); i++) {
			  if (i != 0) document.write("&nbsp;&nbsp;");
				
			  var cellItem = columnItem.getChildAt(i);
				var refItem = cellItem;
			
				if (refItem != null) {
					if (cellItem == currentItem) {
						document.write('<span class="linkCurrent">');
						document.write(i + 1);
						//document.write('|');
						//document.write('<img src="images/symbols/sym_nav_cell.gif" width="9" height="9" border="0" align="baseline">');
						document.write('</span>');
					} else {
						document.write('<a class="link" href="#" onClick="stub.getAPI().gotoItemWithID(\''+refItem.identifier+'\')">');
	  				document.write(i + 1);
						//document.write('|');
						//document.write('<img src="images/symbols/sym_nav_cellsmall.gif" width="9" height="9" border="0" align="baseline">');
						document.write('</a>'); 
					}
				}
			}
		} else {
			document.write('<span class="linkCurrent">');
			document.write("1");
			//document.write('|');
			//document.write('<img src="images/symbols/sym_nav_cell.gif" width="9" height="9" border="0" align="baseline">');
			document.write('</span>');

		}
	}
}
*/

function Nav_gotoPreviousRow() {
	var api = stub.getAPI();
	var nextItem = api.getPreviousRowOf(api.getCurrentItem());
  if (nextItem != null) {
	  	api.gotoItem(nextItem);
	} else {
	//api.gotoMenu();
	}
}

function Nav_gotoNextRow() {
	var api = stub.getAPI();
	var nextItem = api.getNextRowOf(api.getCurrentItem());
  if (nextItem != null) {
	  	api.gotoItem(nextItem);
	} else {
	//api.gotoMenu();
	}
}

function Nav_writeButtons() {
	var api = stub.getAPI();
	if (api.isLoggedIn() && api.mode == api.MODE_COURSE) {
		document.writeln('<a class="button" href="#" onclick="nav.gotoPreviousRow()">'+api.labels.get('toc.previous')+'</a>');
		document.writeln('&nbsp;&nbsp;');
		document.writeln('<a class="button" href="#" onclick="nav.gotoNextRow()">'+api.labels.get('toc.next')+'</a>');
	}
}

function Nav() {
	this.writeColumns = Nav_writeColumns;
	this.writeCells = Nav_writeCells;
	this.writeButtons = Nav_writeButtons;
	this.gotoPreviousRow = Nav_gotoPreviousRow;
	this.gotoNextRow = Nav_gotoNextRow;
}

var nav = new Nav();
